In [6]:
import numpy as np 
import pandas as pd 
import csv

In [7]:
df = pd.read_csv('/Users/rohit/A-December-of-Algorithms/src/docs/Dec21-Exchange_Rates.csv',encoding = "ISO-8859-1")
df

                                 LOCATION    VALUE
0                               Argentina     16.6
1                               Australia      1.3
2                                 Austria      0.9
3                                 Belgium      0.9
4                                  Brazil      3.2
5                                Bulgaria      1.7
6                                  Canada      1.3
7                                   Chile    648.8
8            China (People's Republic of)      6.8
9                                Colombia   2951.3
10                             Costa Rica    567.5
11                                Croatia      6.6
12                                 Cyprus      0.9
13                         Czech Republic     23.4
14                                Denmark      6.6
15                                Estonia      0.9
16               Euro area (19 countries)      0.9
17          European Union (28 countries)      0.9
18                                Finland      0.9
19  Former Yugoslav Republic of Macedonia     54.7
20                                 France      0.9
21                                Germany      0.9
22                                 Greece      0.9
23                                Hungary    274.4
24                                Iceland    106.8
25                                  India     65.1
26                              Indonesia  13380.9
27                                Ireland      0.9
28                                 Israel      3.6
29                                  Italy      0.9
30                                  Japan    112.2
31                                  Korea  1Â 130.4
32                                 Latvia      0.9
33                              Lithuania      0.9
34                             Luxembourg      0.9
35                                  Malta      0.9
36                                 Mexico     18.9
37                            Netherlands      0.9
38                            New Zealand      1.4
39                                 Norway      8.3
40                                   Peru      3.3
41                                 Poland      3.8
42                               Portugal      0.9
43                                Romania      4.1
44                                 Russia     58.3
45                           Saudi Arabia      3.8
46                        Slovak Republic      0.9
47                               Slovenia      0.9
48                           South Africa     13.3
49                                  Spain      0.9
50                                 Sweden      8.5
51                            Switzerland        1
52                                 Turkey      3.6
53                         United Kingdom      0.8
54                          United States        1

In [18]:
fromc = input("From country : ")
amt = float(input("Currency you have : "))
toc = input("To country : ")

From country : India
Currency you have : 1000
To country : Spain

In [19]:
# csv to Dictionary Convert
with open('/Users/rohit/A-December-of-Algorithms/src/docs/Dec21-Exchange_Rates.csv', mode='r',encoding = "ISO-8859-1") as infile:
    reader = csv.reader(infile)
    mydict = {rows[0]:rows[1] for rows in reader}

{'LOCATION': 'VALUE',
 'Argentina': '16.6',
 'Australia': '1.3',
 'Austria': '0.9',
 'Belgium': '0.9',
 'Brazil': '3.2',
 'Bulgaria': '1.7',
 'Canada': '1.3',
 'Chile': '648.8',
 "China (People's Republic of)": '6.8',
 'Colombia': '2951.3',
 'Costa Rica': '567.5',
 'Croatia': '6.6',
 'Cyprus': '0.9',
 'Czech Republic': '23.4',
 'Denmark': '6.6',
 'Estonia': '0.9',
 'Euro area (19 countries)': '0.9',
 'European Union (28 countries)': '0.9',
 'Finland': '0.9',
 'Former Yugoslav Republic of Macedonia': '54.7',
 'France': '0.9',
 'Germany': '0.9',
 'Greece': '0.9',
 'Hungary': '274.4',
 'Iceland': '106.8',
 'India': '65.1',
 'Indonesia': '13380.9',
 'Ireland': '0.9',
 'Israel': '3.6',
 'Italy': '0.9',
 'Japan': '112.2',
 'Korea': '1\xa0130.4',
 'Latvia': '0.9',
 'Lithuania': '0.9',
 'Luxembourg': '0.9',
 'Malta': '0.9',
 'Mexico': '18.9',
 'Netherlands': '0.9',
 'New Zealand': '1.4',
 'Norway': '8.3',
 'Peru': '3.3',
 'Poland': '3.8',
 'Portugal': '0.9',
 'Romania': '4.1',
 'Russia': '58.3',
 'Saudi Arabia': '3.8',
 'Slovak Republic': '0.9',
 'Slovenia': '0.9',
 'South Africa': '13.3',
 'Spain': '0.9',
 'Sweden': '8.5',
 'Switzerland': '1',
 'Turkey': '3.6',
 'United Kingdom': '0.8',
 'United States': '1'}